- lib/moon/components/accordion.ex
- add pull_a_side class
- optional `overflow-hidden`
> Accordion changes

- lib/moon/components/text_input/subcomponents/text_input_basic.ex
- lib/moon/components/text_input/subcomponents/text_input_inner_label.ex
- lib/moon/components/text_input/subcomponents/text_input_password.ex
> fix: fix for buttons on text input icons [MDS-219]

- lib/moon/render_helpers.ex
This PR adds Render Helpers functions for LiveComponent.
> feat: added render helper functions

- assets/js/hooks/index.js
- assets/js/hooks/popover.js
- assets/package-lock.json
- assets/package.json
- lib/moon/components/dialog/modal.ex
- lib/moon/components/popover.ex
- lib/moon/components/select/dropdown/option/renderer.ex
- lib/moon_web/pages/components/dialog/modal_page.ex
- lib/moon_web/pages/components/dialog/popover_page.ex
> Fix popover (Switch to Popper.js)

- lib/moon_web/components/table/table.ex
minor color fix for text in table
> text-color in table cross-side fix [MDS-230]

- scripts/typescript/figma-importer.ts
added duplicate key warning to figma importer
> figma importer: duplicate key warning

- lib/moon/components/accordion.ex
- lib/moon/components/button.ex
- lib/moon_web/components/preview_code_button.ex
- lib/moon_web/pages/components/accordion_page.ex
- lib/moon_web/pages/components/avatar_page.ex
- lib/moon_web/pages/components/breadcrumb_page.ex
- lib/moon_web/pages/components/button_page.ex
minor accordeon api change
few pages polish on site
code/preview switcher align
> [MDS-270] minor site polish & code/preview switcher

- README.md
- assets/tailwind.config.js
- lib/moon/components/table.ex
- lib/moon/components/table/column.ex
- lib/moon_web/pages/components/table_page.ex
> fix: [MDS-282] Table

- lib/moon/components/select/multi_select.ex
- lib/moon/components/select/single_select.ex
- lib/moon/components/text_input/subcomponents/text_input_basic.ex
- lib/moon/components/text_input/subcomponents/text_input_password.ex
- lib/moon_web/pages/components/select/single_select_page.ex
> Fix single/multi select

- lib/moon/components/table.ex
- lib/moon/components/text_input/subcomponents/text_input_basic.ex
- lib/moon/components/text_input/subcomponents/text_input_password.ex
- lib/moon/design/table.ex
- lib/moon_web/components/left_menu.ex
- lib/moon_web/pages/components/table_page.ex
- lib/moon_web/pages/components/text_input/text_input_page.ex
- lib/moon_web/pages/design/table_page.ex
- lib/moon_web/router.ex
- previous table component is back also
- left menu has new point Components V2 
- text input examples fix
> Table component v2/1

- lib/moon/design/breadcrumb/collapsed.ex
- lib/moon/design/breadcrumb/extended.ex
- lib/moon_web/pages/components/breadcrumb_page.ex
- lib/moon_web/pages/design/breadcrumb_page.ex
- Added Aria support for Breadcrumb v2
- Added Deprecation warning for Breadcrumb v1
> fix: [MDS-331] Breadcrumb v2

- config/config.exs
- lib/moon/design/accordion.ex
- lib/moon/design/accordion/content.ex
- lib/moon/design/accordion/header.ex
- lib/moon/design/tabs.ex
- lib/moon/design/tooltip.ex
- lib/moon/design/tooltip/arrow.ex
- lib/moon/design/tooltip/content.ex
- lib/moon/helpers/merge_class.ex
- lib/moon/helpers/styled.ex
- lib/moon_web/components/left_menu.ex
- lib/moon_web/pages/components/accordion_page.ex
- lib/moon_web/pages/design/accordion_page.ex
- lib/moon_web/pages/design/tooltip_page.ex
- lib/moon_web/router.ex
- test/moon/helpers/merge_class_test.exs
- subj
- Tooltip fix - no js, css only
- some merge_class improvement
> MDS-333 Accordion-v2

- lib/moon/design/button.ex
- lib/moon/design/button/icon_button.ex
Hover still doesn't work properly on text and need to be fixed (either separate event(s) to be added or filter approach?)
> fix: [MDS-271] Button v2 - hover 

- lib/moon/design/button.ex
- lib/moon/design/button/icon_button.ex
- mix.exs
- Fixing loader size to be dependent on button size
- Whitespace-nowrap to button text
> fix: [MDS-271] Button v2

- lib/moon/design/circular_progress.ex
- lib/moon/design/progress.ex
making string => css_class for classes properties
> chore: few minor fixes for progresses

- lib/moon/design/modal.ex
- lib/moon/design/modal/panel.ex
- lib/moon_web/examples/design/chip_example/modal_example/default.ex
- lib/moon_web/examples/design/chip_example/modal_example/with_big_content.ex
- lib/moon_web/examples/design/chip_example/modal_example/with_select.ex
- lib/moon_web/examples/design/chip_example/modal_example/with_styled_content.ex
- lib/moon_web/pages/design/modal_page.ex
- modal behaviour fixed
- examples updated
- test_id added
> fix: [MDS-361] Modal v2

- lib/moon/components/table.ex
- lib/moon/design/table.ex
- lib/moon/design/table/column.ex
- lib/moon/helpers/make_list.ex
- lib/moon_web/components/props_table.ex
- lib/moon_web/examples/design/bottom_sheet_example/custom_height.ex
- lib/moon_web/examples/design/switch_example/using_with_forms.ex
- lib/moon_web/examples/design/table_example/responsive.ex
- lib/moon_web/examples/design/table_example/sorting.ex
- lib/moon_web/pages/design/switch_page.ex
- lib/moon_web/pages/design/table_page.ex
here is an example for responsive Table v2 components. can be easly propagated to v1 also
> fix: responsive table example

- assets/js/hooks/animation.js
will work as a charm after live_view will publish these changes - https://github.com/phoenixframework/phoenix_live_view/commit/9cc41da5401b3fe5b21c84430354208a69f263ec
> fix: push_patch 

- lib/moon/components/text_input.ex
- lib/moon/components/text_input/input.ex
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/min
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max
> Add min and max to TextInput

- lib/moon/design/form/combobox.ex
- lib/moon_web/components/props_table.ex
- lib/moon_web/examples/design/form/combobox_example/default.ex
- lib/moon_web/examples/design/form/combobox_example/multiple.ex
bug explained here - https://coingaming.slack.com/files/U02UTEFCKM4/F07BECQR9PV/screen_recording_2024-07-08_at_13.19.00.mov
> fix: fixing combobox behaviour when filtering
